import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/deposit_model.dart';

class DepositRepository {
  final SupabaseClient _client;

  DepositRepository(this._client);

  Future<List<DepositModel>> getDeposits({
    DateTime? startDate,
    DateTime? endDate,
    String? category,
  }) async {
    var query = _client.from('deposits').select();

    if (startDate != null) {
      query = query.gte('created_at', startDate.toIso8601String());
    }
    if (endDate != null) {
      // Add one day to include the end date fully
      final nextDay = endDate.add(const Duration(days: 1));
      query = query.lt('created_at', nextDay.toIso8601String());
    }
    if (category != null && category.isNotEmpty && category != 'Semua') {
      query = query.eq('category', category);
    }

    final response = await query.order('created_at', ascending: false);

    return (response as List).map((e) => DepositModel.fromJson(e)).toList();
  }

  Future<DepositModel> createDeposit(DepositModel deposit) async {
    final data = deposit.toJson();
    data.remove(
      'id',
    ); // ID generated by DB or if we passed it, usually DB default gen is better but here we use UUID v4 from client often.
    // Wait, the user usually uses UUID v4 from client in this codebase (seen in PaymentEntryScreen).

    // Let's check PaymentEntry logic again. It generates UUID v4.
    // But usually Supabase can handle it.
    // I will stick to sending all data if ID is generated by client.

    // Actually, createPayment in PaymentRepo removes 'id'.
    // "paymentData.remove('id');"
    // So ID is likely auto-generated by Supabase (uuid_generate_v4()).

    final response = await _client
        .from('deposits')
        .insert(data)
        .select()
        .single();

    return DepositModel.fromJson(response);
  }

  // Calculate total deposits manually or via RPC if available.
  // Using client-side sum for list view consistency for now as dataset is small,
  // or define a method that uses SQL sum.
  Future<int> getTotalDeposits() async {
    // If heavy, use RPC. For now, fetch 'amount' only.
    final response = await _client.from('deposits').select('amount');
    final List<dynamic> data = response as List<dynamic>;
    if (data.isEmpty) return 0;
    return data.fold<int>(0, (sum, item) => sum + (item['amount'] as int));
  }

  Future<void> updateDeposit(DepositModel deposit) async {
    await _client
        .from('deposits')
        .update(deposit.toJson())
        .eq('id', deposit.id);
  }

  Future<void> deleteDeposit(String id) async {
    await _client.from('deposits').delete().eq('id', id);
  }
}
